#!/bin/bash
# This hook is run after this virtualenv is activated.

# ld
export __OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH

# pkg-config
export __OLD_PKG_CONFIG_PATH=$PKG_CONFIG_PATH
export PKG_CONFIG_PATH=$VIRTUAL_ENV/lib/pkgconfig:$PKG_CONFIG_PATH

# gcc
export __OLD_INCLUDE_PATH=$INCLUDE_PATH
export __OLD_LIBRARY_PATH=$LIBRARY_PATH
export LIBRARY_PATH=$VIRTUAL_ENV/lib:$LIBRARY_PATH
export INCLUDE_PATH=$VIRTUAL_ENV/include:$INCLUDE_PATH
