#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# set history settings
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

. /usr/share/git/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWCOLORHINTS=1
color_prompt=yes
if [ "$color_prompt" = yes ]; then
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")\n\$ '
else
    PS1='\u@\h:\w\$ '
fi
unset color_prompt

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# setup python virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
. /usr/bin/virtualenvwrapper_lazy.sh

# pip bash completion start
_pip_completion()
{
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 ) )
}
complete -o default -F _pip_completion pip

export GIT_AUTHOR_NAME="Steinn Steinsen"
export GIT_AUTHOR_EMAIL="steinn@clara.is"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export PATH=$PATH:$HOME/bin
export EDITOR="emacsclient -nw -c"
export PATH=$PATH:$HOME/work/birdcore/scripts/bin

# start ssh keychain
eval $(keychain --eval --agents ssh -Q --quiet id_rsa)

eval `dircolors $HOME/.dir_colors`
