# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

export LESS="-R"

# some more ls aliases
alias ls='ls --color=auto --group-directories-first -h'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# git
alias g='git'
alias gs='git status'
alias gb='git branch'
alias gd='git diff'
alias gf='git fetch'
alias gr='git rebase'
alias gp='git push'
alias gfr='git fetch; git rebase'

alias birdcore='cd ~/work/birdcore'
alias birdcore_dev='. ~/.virtualenvs/birdcore/bin/activate'

# emacs
alias e='emacsclient -t'
alias ec='emacsclient -c'